#! /bin/sh

### BEGIN INIT INFO
# Provides:		sshd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:         2
# Short-Description:	Firewall
### END INIT INFO

set -e

start(){
	/sbin/iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
	/sbin/iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
	/sbin/iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT

	/sbin/iptables -A FORWARD -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
	/sbin/iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
	/sbin/iptables -A INPUT -i eth1 -p icmp --icmp-type echo-reply -m limit --limit 1/s -j DROP
	/sbin/iptables -A FORWARD -p tcp -m limit --limit 1/s -j ACCEPT
	/sbin/iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
	/sbin/iptables -A FORWARD -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s -j ACCEPT
	/sbin/iptables -A FORWARD --protocol tcp --tcp-flags ALL SYN,ACK -j DROP
	/sbin/iptables -A INPUT -m state --state INVALID -j DROP
	/sbin/iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
	/sbin/iptables -N VALID_CHECK
	/sbin/iptables -A VALID_CHECK -p tcp --tcp-flags ALL FIN,URG,PSH -j DROP
	/sbin/iptables -A VALID_CHECK -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP
	/sbin/iptables -A VALID_CHECK -p tcp --tcp-flags ALL ALL -j DROP
	/sbin/iptables -A VALID_CHECK -p tcp --tcp-flags ALL FIN -j DROP
	/sbin/iptables -A VALID_CHECK -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
	/sbin/iptables -A VALID_CHECK -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
	/sbin/iptables -A VALID_CHECK -p tcp --tcp-flags ALL NONE -j DROP

	echo "Firewall start"
}

stop(){
	# clear all chains
	iptables -F INPUT
	iptables -F OUTPUT
	iptables -F FORWARD
	iptables -F -t filter
	iptables -F POSTROUTING -t nat
	iptables -F PREROUTING -t nat
	iptables -F OUTPUT -t nat
	iptables -F -t nat
	iptables -t nat -F
	iptables -t mangle -F
	iptables -X

	# clear all counters
	iptables -Z
	iptables -t nat -Z
	iptables -t mangle -Z

	# accept all by default
	iptables -P INPUT ACCEPT
	iptables -P OUTPUT ACCEPT
	iptables -P FORWARD ACCEPT

	echo "Firewall stop"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  *)
	log_action_msg "Usage: /etc/init.d/firewall {start|stop|restart}" || true
	exit 1
esac

exit 0

